/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['import[_ngcontent-%COMP%] { Component } from[_ngcontent-%COMP%]   \'@angular/core\'\n\n@Component([_ngcontent-%COMP%]{\n    selector: \'mellow-world\',\n    templateUrl: \'./mellowWorld.template.html\',\n    styles: [`import { Component } from \'@angular/core\'\n\n@Component({\n    selector: \'mellow-world\',\n    templateUrl: \'./mellowWorld.template.html\',\n    styles: [`import { Component } from \'@angular/core\'\n\n@Component({\n    selector: \'mellow-world\',\n    templateUrl: \'./mellowWorld.template.html\',\n    styles: [`#mellow-world {\n    width: 400px;\n    font-family: sans-serif;\n    background: #99E343;\n}`]\n})\n\nexport class MellowWorldComponent { }`]\n})\n\nexport class MellowWorldComponent { }`]\n})\n\nexport[_ngcontent-%COMP%]   class[_ngcontent-%COMP%]   MellowWorldComponent[_ngcontent-%COMP%] { }'];